package com.br.amber.jogodastrespistas.enums

enum class RoomStatusesEnum{
    WAITING_GUEST,
    GUEST_JOINED,
    PLAYING,
    FINISHED,
    ROUND_FINISHED_WITH_WINNER,
    ROUND_FINISHED_WITHOUT_WINNER,
    ROUND_FINISHED_WITHOUT_ANSWER_FROM_OWNER,
    ROUND_FINISHED_WITHOUT_ANSWER_FROM_GUEST,
    ABANDONED,
    VERIFYING_ANSWER,
    CHOOSING_WORD_NEXT_ROUND,
    CHOOSING_WORD_NEW_GAME,
    GOT_WRONG_ANSWER,
    GOT_CORRECT_ANSWER,
    GOT_NO_ANSWER_OWNER,
    GOT_NO_ANSWER_GUEST,
    OWNER_WANTS_PLAY_AGAIN,
    GUEST_WANTS_PLAY_AGAIN


}